site_name: "UVSQ_EN3889_TP_Python"
site_url: "https://nicoudart.github.io/UVSQ_EN3889_TP_Python"
site_author: "Nicolas OUDART"

theme:
  name: readthedocs
nav:
  - Introduction: index.md
  - Préparation: Preparation.md
  - TP1: TP1.md
  - TP2: TP2.md
  - TP3: TP3.md
  - Bonus: Bonus.md
  - Examen 2025: examen_2025.md